send_otp:
    path: '/api/otp'
    methods: [POST]
    defaults: { _controller: AppBundle:API\OTP:sendEmail }
validate_otp:
    path: '/api/otp/validate'
    methods: [POST]
    defaults: { _controller: AppBundle:API\OTP:validate }
catch_all:
    path: /{catch_all}
    defaults:
        { _controller: AppBundle:Default:index, catch_all: 1 }
    requirements:
        catch_all: "[\s\S]+"